name: lint
on: [push]
jobs:
  check-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Install
          run:
            make install
      - name: Linter-check
        run:
            make lint